[package]
name = "pessimistic-proof-sp1"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

members = [
    "pessimistic-proof",
]

[dependencies]
bincode = "1.3.3"
pessimistic-proof = { path = "./pessimistic-proof" }
sp1-zkvm = "1.1.1"

[build-dependencies]
sp1-cli = "1.1.1"
