[package]
name = "program-valida"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
pessimistic-proof-core = { path = "../pessimistic-proof-core", default-features = false }
valida-rs = { git = "https://github.com/lita-xyz/valida-rs.git", branch = "no-deps" }
